version: '3.3'
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - '${APP_PORT_EXT:-3000}:3000'
    environment:
      MONGO_APP_PWD: $MONGO_APP_PWD
      STRAT_URL: $STRAT_URL

  db:
    image: mongo:5.0.6
    restart: unless-stopped
    volumes:
      - './mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh'
      - 'srvexo-data-db:/data/db'
    environment:
      MONGO_INITDB_USER: $MONGO_APP_USER
      MONGO_INITDB_PASSWORD: $MONGO_APP_PWD
      MONGO_INITDB_DATABASE: $MONGO_DB_NAME

volumes:
  srvexo-data-db:
